services:
  postgres:
    image: postgres:latest
    container_name: bookamovie-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: bookamovie
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: movie_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - bookamovie-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U movie_user -d bookamovie"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bookamovie-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bookamovie.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - bookamovie-network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  bookamovie-network:
    driver: bridge